# Generated by Django 3.1.4 on 2021-01-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='reseiver',
            new_name='receiver',
        ),
    ]
